service:
  name: wah-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 720
  timeout: 900

functions:
  auctions:
    handler: controllers/auction.handler
    events:
      - http:
          method: post
          path: auction
          cors:
            origin: '*'

  items:
    handler: controllers/item.handler
    events:
      - http:
          method: any
          path: item
          cors:
            origin: '*'

      - http:
          method: any
          path: item/{id}
          cors:
            origin: '*'
  pets:
    handler: controllers/pet.handler
    events:
      - http:
          method: any
          path: pet
          cors:
            origin: '*'

      - http:
          method: any
          path: pet/{id}
          cors:
            origin: '*'
  recipes:
    handler: controllers/recipe.handler
    events:
      - http:
          method: any
          path: recipe
          cors:
            origin: '*'

      - http:
          method: any
          path: recipe/{id}
          cors:
            origin: '*'
  character:
    handler: controllers/character.handler
    events:
      - http:
          method: post
          path: character
          cors:
            origin: '*'
  realm:
    handler: controllers/realm.handler
    events:
      - http:
          method: post
          path: realm
          cors:
            origin: '*'
  test:
    handler: controllers/test.handler
    events:
      - http:
          method: any
          path: test